# load packages

import pandas as pd
import os
from snakemake.utils import validate
from snakemake.utils import min_version

min_version("9.5.1")

# configuration
configfile: "../config/config.yaml"

# load samples
gt_params = pd.read_table(
    "../config/gt_params.tsv", sep="\t", dtype={"ID": str}
).set_index(["ID"], drop=False)

# empirical data
reads = pd.read_table(
    "../config/reads.tsv", sep="\t", dtype={"sample": str}
).set_index(["sample"], drop=False)

reads = reads[reads['sample'].str.contains('^S')]

# fst simulations
fst_params = pd.read_table(
    "../config/fst_params.tsv", sep="\t", dtype={"ID": str}
).set_index(["ID"], drop=False)

sampling_times = pd.read_table(
    "../config/sampling_times.tsv", sep="\t", dtype={"ID": str}
).set_index(["ID"], drop=False)

rule all_gt_sims:
    input:
        expand("slim_results/{ID}_neutfreqs.tsv", ID=gt_params["ID"])

rule all_fst_sims:
    input:
        #"fst_results.txt",
        expand("msprime_results/{ID}.txt", ID=fst_params["ID"]),
        expand("gcta_results/{ID}.fst", ID=fst_params["ID"])
        #expand("msprime_results/{ID}.txt", ID=fst_params["ID"])

rule all_poolseq:
    input:
        expand("freqk_call_results/{sample}.txt", sample=reads["sample"])

#rule all_seed_mix:
#    input:
#        expand("freqk_call_results/{sample}.txt", sample=config["seed_samples"])

include: "rules/freqk.smk"
include: "rules/fastp.smk"
include: "rules/msprime.smk"
include: "rules/fst_sim.smk"
#include: "rules/legacy/kmc.smk"
#include: "rules/legacy/kmc_contam_db.smk"
#include: "rules/legacy/kmc_rm_contam.smk"
#include: "rules/legacy/kmc_filter.smk"
#include: "rules/legacy/multiqc.smk"
#include: "rules/legacy/bwa_index.smk"
#include: "rules/legacy/bwa_mem.smk"
#include: "rules/legacy/samtools.smk"
#include: "rules/legacy/varscan.smk"
