# Simulation parameters
sim_fasta: "/global/scratch/users/milesroberts/moi_lab_projects/grenenet-phase2/resources/Athaliana_447_TAIR10_chr1.fa"

sim_vcf: "/global/scratch/users/milesroberts/moi_lab_projects/grenenet-phase2/resources/greneNet_final_v1.1_chr1.recode.vcf.gz"


# Empirical sequence data parameters

reference: "/global/scratch/users/milesroberts/moi_lab_projects/grenenet-phase2/resources/Athaliana_447_TAIR10.fa"

# Phase 1 pool-seq
# freqk_index: "/global/home/users/milesroberts/tmp/tati_cam5_alignments/index.txt"
# freqk_index: "/global/scratch/users/milesroberts/tmp/tati_cam5_alignments/var_index.txt"
freqk_index: "/global/scratch/users/milesroberts/moi_lab_projects/grenenet-phase2/resources/ref_index_greneNet.txt"

phase1_poolseq_root: "/global/home/users/xingwu/moi_lab/projects/grenenet-phase1/fastq/pool_sequencing/" 

# command to get list
# ls /global/home/users/xingwu/moi_lab/projects/grenenet-phase1/fastq/ncbi_submission/submission_2000_2415/MLFH* | sed 's:.*/::g' | sed 's:_.*::g'| sort -u | sed 's:^: - ":g'| sed 's:$:":g'

# Adaptest samples
adaptest_root: "/global/home/users/ruthkepstein/moi_lab/projects/adaptest_N800_deepseq/"

adapteset_samples: ~/config/samples_adaptest.tsv

# SEED MIX ===================================================================
seed_root: "/global/home/users/xingwu/moi_lab/projects/grenenet-phase1/fastq/ncbi_submission/submission_2000_2415/"

seed_suffix:
 - ".1_P.fq.gz"
 - ".2_P.fq.gz"

seed_samples: ~/config/samples_seed_mix.tsv

# Pooled samples ====================================================================
pool_root: "/global/scratch/projects/fc_moilab/projects/grenenet_phase2_poolseq/"

pool_samples: ~/config/samples_pool.tsv

# kmc parameters ============================================================================
k: 31
contam_mincount: 2
sample_mincount: 4

# fastp parameters ==========================================================================
unqualLimit: 40
qualThresh: 30
windowLength: 1
nBaseLimit: 5

# contaminants to include in read QC =========================================================

## contaminants to download from ncbi
#ncbi_contams:
        # - "human"
# - "viruses"
# - "eubacteria"
# - "fungi"
# - "archaea"

## custom contaminants, user provides fasta file
custom_contams:
 - "grenenet_pseudogenomes" 
   # - "grenenet-specific-kmers"
   #- "Athaliana_447_TAIR10"

phase1_poolseq_samples: ~/config/samples_phase1_poolseq.tsv

phase1_poolseq_suffix:
 - "_1.fq.gz"
 - "_2.fq.gz"

# phase 2 poolseq ==========================================
phase2_poolseq_root: "/global/scratch/projects/fc_moilab/projects/grenenet_phase2_poolseq/"

phase2_poolseq_suffix:
 - "_R1_001.fastq.gz"
 - "_R2_001.fastq.gz"

phase2_poolseq_samples: ~/config/samples_phase2_poolseq.tsv